// /app/layout.js

"use client";
/**
 * Marks this file as a **client-side** component in Next.js.
 * This is required because it uses React hooks and context providers that rely on client-side rendering.
 */

// -------------------- IMPORTS --------------------

// Global CSS styles for the entire application.
// This file typically defines global typography, colors, margins, and resets.
import "./globals.css";

// Importing the "Inter" font from Google Fonts via Next.js built-in font optimization feature.
// The `Inter` font will be applied to all text in the application to maintain consistent typography.
import { Inter } from "next/font/google";

// Importing the application context provider, which supplies global state and shared logic
// (e.g., alerts, messages, theme preferences, etc.) across all components in the app.
import { AppProvider } from "./components/context/AppContext";

// Importing the application's custom Material UI theme wrapper.
// `AppTheme` manages light/dark mode and other theme-related configurations for consistent styling.
import AppTheme from "./shared-theme/AppTheme";

// -------------------- FONT INITIALIZATION --------------------

// Initializes the Inter font and restricts it to the "latin" character subset for optimized loading performance.
const inter = Inter({ subsets: ["latin"] });

// -------------------- METADATA (COMMENTED OUT) --------------------
/**
 * This section defines SEO-related information such as:
 * - `title`: The default page title for the app.
 * - `description`: A short description that helps search engines understand the site's purpose.
 */
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// -------------------- ROOT LAYOUT COMPONENT --------------------

/**
 * RootLayout — The foundational layout component that wraps every page in the Next.js application.
 *
 * Responsibilities:
 * - Defines the HTML structure (`<html>` and `<body>` tags) for all routes.
 * - Applies global font and theme settings.
 * - Provides application-wide state management through React Context.
 *
 * @param {object} props
 * @param {React.ReactNode} props.children - The nested page or component rendered inside the layout.
 * @returns {JSX.Element} The complete root HTML structure with global providers applied.
 */
export default function RootLayout({ children }) {
  return (
    // Defines the HTML language attribute for accessibility and SEO.
    <html lang="en">
      {/* The <body> element applies the global Inter font style */}
      <body className={inter.className}>
        {/* 
          AppTheme: Wraps the application with a Material UI ThemeProvider.
          - Ensures consistent color palette and component styling.
          - Handles dynamic theme changes (e.g., light/dark modes).
        */}
        <AppTheme>
          {/* 
            AppProvider: Wraps all children components with a React Context provider.
            - Supplies global state and shared methods to all nested components.
            - Reduces prop drilling and improves state consistency across the app.
          */}
          <AppProvider> {children}</AppProvider>
        </AppTheme>
      </body>
    </html>
  );
}
