"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { createTheme, ThemeProvider } from "@mui/material/styles";

import { CacheProvider } from "@emotion/react";
import createCache from "@emotion/cache";
import { prefixer } from "stylis";
import rtlPlugin from "@mui/stylis-plugin-rtl";

// Create rtl cache
const rtlCache = createCache({
  key: "muirtl",
  stylisPlugins: [prefixer, rtlPlugin],
});

const theme = createTheme({
  direction: "rtl",
});

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body className={inter.className}>
        {" "}
        <CacheProvider value={rtlCache}>
          <ThemeProvider theme={theme}> {children}</ThemeProvider>
        </CacheProvider>
      </body>
    </html>
  );
}
